# Generated by Django 3.2.4 on 2024-10-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_stamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'return_code',
            },
        ),
    ]
