# Generated by Django 5.1.2 on 2024-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_returncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
