# Generated by Django 5.1.2 on 2024-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_department_user_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rental_code',
            },
        ),
    ]
