# Generated by Django 5.1.2 on 2024-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_renting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rental_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
